### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by CJJC1220** [ourfool/picture-to-gds#3]
do you know how to convert gds-to-pictures,hope you can share one.thank you.

**Comment by ourfool** [comment]
Hello.
It seems to be possible to write a simple python script to convert GDSII to image.
I think the page shown in below would be helpful.
http://boolean.klaasholwerda.nl/interface/bnf/gdsformat.html
Otherwise, you can use free GDS viewer (e.g. https://www.klayout.de/index.php) for opening gds files and taking a screenshot, or exporting the layout in the form of image files.

**Comment by CJJC1220** [comment]
I'm sorry that I can't open the web page. http://boolean.klaasholwerda.nl/interface/bnf/gdsformat.html

**Comment by ourfool** [comment]
Please look at the link below.
https://en.wikipedia.org/wiki/GDSII
External links→GDSII™ Stream Format Manual (B97E060), Release 6.0 // Calma, February 1987
